#      _____                               _____ _____
#    / ____|                        /\   |  __ \_   _|
#   | |  __  __ _ _ __ ___   ___   /  \  | |__) || |
#   | | |_ |/ _` | '_ ` _ \ / _ \ / /\ \ |  ___/ | |
#   | |__| | (_| | | | | | |  __// ____ \| |    _| |_
#   \_____|\__,_|_| |_| |_|\___/_/    \_\_|   |_____|


#The maximum amount of players that can be in one lobby;
lobby-max-players: 120

#Connects to a database reserved for storing coins.
coins-support:
  enabled: false
  username: ""
  password: ""
  port: 3306
  host: ""

#Enables stuff like the wand and save command.
enable-schematic-commands: true