main: dev.nova.gameapi.GameAPI
version: 1.0
name: GameAPI
commands:
  queue:
    description: Queues a player in a game!
    usage: "&c/queue <game> <instance_name>"
  leave:
    description: Makes a player leave a game!
    aliases:
      - l
  lobby:
    description: Moves the player to a lobby. Simmilar to the "leave" command but here the player may use it everywhere.
    usage: "&c/lobby [game]"
  map:
    description: Does a lot of actions with maps like create new ones edit existing ones deleting, etc...
  spectate:
    description: Makes a player spectate a other's game!
  party:
    description: The party API implementation.
    aliases:
      - p
  forcestart:
    description: Starts a queue forcivly
    aliases:
      - fs
  revive:
    description: Revives you!
  spectator:
    description: Makes you a ghost.
  wand:
    description: A wand.
  saveSchematic:
    description: Saves a schematic to a file!
  rejoin:
    description: Rejoins a previous game. (if the instance was capable of doing that)
depend:
  - ProtocolLib
  - SlimeWorldManager