main: dev.nova.gameapi.GAPIPlugin
version: 1.0
name: GameAPI
startup: postworld
api-version: 1.16
commands:
  queue:
    description: Queues a player in a game!
    usage: "&c/queue <game> <instance_name>"
  leave:
    description: Makes a player leave a game!
    aliases:
      - l
  spectate:
    description: Makes a player spectate a other's game!
  party:
    description: The party API implementation.
    aliases:
      - p
  forcestart:
    description: Starts a queue forcivly
    aliases:
      - fs
  revive:
    description: Revives you!
  spectator:
    description: Makes you a ghost.
  wand:
    description: A wand.
  saveSchematic:
    description: Saves a schematic to a file!
depend:
  - ProtocolLib